apiVersion: v1
kind: Pod
metadata:
  name: tell-the-secret
spec:
  containers:
  - name: teller
    image: alpine
    command:
      - "/bin/sh"
      - "-c"
      - "while true; do date -u '+%Y-%m-%dT%H:%M:%SZ:' ; cat /var/my-secret/secret.txt 2>&1 | sed -e 's/^/  - /g'; cat /var/my-secret/added-secret.txt 2>&1 | sed -e 's/^/  - /g'; sleep 3; done"
    volumeMounts:
    - name: my-secret
      mountPath: "/var/my-secret"
      readOnly: true
  volumes:
  - name: my-secret
    secret:
      secretName: the-secret
